### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by YohskDista**
Add french translation to the Fluent XAML Theme Editor according to PR #1

### CODE REVIEW

**Comment by kikisaints** [comment]
Looks like you missed some text on this flyout, otherwise it looks good!

image

**Comment by YohskDista** [comment]
You're right, I missed the resources in `FluentEditorShared`, I will fix that :)

**Comment by kikisaints** [comment]
A lot better, but it still looks like some text on the color picker flyout is missing - it's possible we didn't hook it up properly in the resources file.

Did you not find definitions for the these highlighted regions?
image

**Comment by YohskDista** [comment]
That's weird, I cannot find anything who is not translated.. If there is an error here, then the Spanish files have also this problem no ?

**Comment by kikisaints** [comment]
This looks good now, thank you for your hard work!

**Pull request merged**
